export const types = {
  GET_ALL_CATEGORIES_LOADING: "GET_ALL_CATEGORIES_LOADING",
  GET_ALL_CATEGORIES_SUCSES: "GET_ALL_CATEGORIES_SUCSES",
  GET_ALL_CATEGORIES_ERROR: "GET_ALL_CATEGORIES_ERROR",

  GET_SUB_CATEGORIES_LOADING: "GET_SUB_CATEGORIES_LOADING",
  GET_SUB_CATEGORIES_SUCSES: "GET_SUB_CATEGORIES_SUCSES",
  GET_SUB_CATEGORIES_ERROR: "GET_SUB_CATEGORIES_ERROR",
};
